---
language: java
jdk:
  - oraclejdk8

sudo: false
cache: bundler
addons:
  apt:
    packages:
      - tree
before_install:
  - rvm install 2.2.5
  - rvm use 2.2.5

script:
  - bin/unit-tests.sh
  - bin/journey-test.sh
